# Generated by Django 4.1.4 on 2023-07-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Baner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="This is deleted datetime",
                        null=True,
                        verbose_name="Deleted Datetime",
                    ),
                ),
                (
                    "restored_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="This is Restored Datetime",
                        null=True,
                        verbose_name="Restored Datetime",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        help_text="This is deleted status",
                        verbose_name="Deleted status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        editable=False,
                        help_text="This is active status",
                        verbose_name="Active status",
                    ),
                ),
                ("banner", models.ImageField(upload_to="banner/")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
