# Generated by Django 4.1.4 on 2023-07-06 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="baner",
            old_name="banner",
            new_name="image",
        ),
    ]
