# Generated by Django 4.1.4 on 2023-01-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_offer_remove_order_offer_id_order_offer'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
