# Generated by Django 4.1.4 on 2023-07-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_product_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rate",
            field=models.PositiveIntegerField(default=20),
        ),
    ]
