# Generated by Django 4.1.4 on 2023-08-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_alter_product_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rate",
            field=models.PositiveIntegerField(default=50),
        ),
    ]
