# Generated by Django 4.1.4 on 2023-08-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_alter_product_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="created_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
