# Generated by Django 4.1.4 on 2023-08-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_alter_comment_created_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_time",
            field=models.DateField(auto_now=True),
        ),
    ]
