# Generated by Django 4.1.4 on 2023-08-02 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_alter_comment_created_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="product.product",
            ),
        ),
    ]
