# Generated by Django 4.1.4 on 2023-08-06 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_cart_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
