# Generated by Django 4.1.4 on 2023-08-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_remove_cartitem_cart_remove_cartitem_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
