# Generated by Django 4.1.4 on 2023-01-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile/%Y/%m/%d/'),
        ),
    ]
