# Generated by Django 4.1.4 on 2023-08-09 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_account_groups_account_is_superuser_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="address",
            new_name="city",
        ),
        migrations.RemoveField(
            model_name="account",
            name="postal_code",
        ),
        migrations.AddField(
            model_name="address",
            name="Alley",
            field=models.CharField(default=None, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="Housebell",
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="Housenumber",
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="Postal_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="street",
            field=models.CharField(default=None, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="account_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
