# Generated by Django 4.1.4 on 2023-08-12 13:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_rename_address_address_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishing_item",
            name="wishing",
        ),
        migrations.DeleteModel(
            name="Wishing",
        ),
        migrations.DeleteModel(
            name="Wishing_item",
        ),
    ]
